export enum Country {
  Belarus = 'Belarus',
  Poland = 'Poland',
  Ukraine = 'Ukraine',
  UnitedStates = 'United States',
  Uzbekistan = 'Uzbekistan',
  Kazakhstan = 'Kazakhstan',
  Turkey = 'Turkey',
  Slovakia = 'Slovakia',
  CzechRepublic = 'Czech Republic',
  Hungary = 'Hungary',
  Romania = 'Romania',
  Slovenia = 'Slovenia',
  Estonia = 'Estonia',
  Latvia = 'Latvia',
  Canada = 'Canada',
  Germany = 'Germany',
  France = 'France',
  Spain = 'Spain',
  Italy = 'Italy',
  UnitedKingdom = 'United Kingdom',
  Australia = 'Australia',
  Brazil = 'Brazil',
  Japan = 'Japan',
  China = 'China',
  India = 'India',
}
